### ISSUE TITLE
make fails in CRF++-0.51 directory due to missing include

### ISSUE THREAD

**Issue by killeent** [knmnyn/ParsCit#16]
When trying to install CRF++ using make the build fails because the file path.h is missing an include that defines size_t. This can easily be added by adding #include <cstdlib> to that file and recompiling. I'd submit a PR but the source file is in the CRF .tar.gz.

**Comment by knmnyn** [comment]
@killeent , thanks for your issue.  We have directly embedded the CRF source code, but since we don't manage that project we've left that as-is.  We will include your point into the troubleshooting section of the ParsCit FAQ for others' reference and will acknowledge you.  Thanks again!
