### ISSUE TITLE
Author name order in references (first name + last name)

### ISSUE THREAD

**Issue by jgrossi** [knmnyn/ParsCit#18]
Hi there! Here I'm again ;-)

Extracting references from PDF papers I have a fixed author name format like `M Delio` or `DM McDonald-McGinn`. Is there any way to set the order of extraction like `last_name` and after `first_name` or the opposite? Is this customizable?

Thanks! Regards.

**Comment by knmnyn** [comment]
Hi there, thanks for your interest.  Unfortunately, no there's no direct way to customize ParsCit to do this.  We'd recommend two ways to get what you want: 1) use a post-process to enforce the constraints that you have in your dataset, 2) or if you have more time, you can re-train ParsCit by changing the training data to change the `<author>` tag into `<author_last>` and `<author_first>` tags.

Hope that helps!

**Comment by jgrossi** [comment]
Thanks for the response @knmnyn! I think is easier to do a post-process and change when the first name came first.

Thank you. Regards.
