### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by dwatsonbynes** [knmnyn/ParsCit#22]
I am using Parscit in windows. But I only have a single partition on my PC, that is, C:. Now the issue arises that it tries to create temporary files. I have tried to change path, but still the error persists. Can you help me out? 
![image](https://cloud.githubusercontent.com/assets/6436348/16333665/145ef434-3a1a-11e6-9ab5-306fc40d8f0f.png)

**Comment by cmkumar87** [comment]
Hi there! 

Thanks for using parsCit!

We don't support the windows version of parsCit since we did not develop that version. So I am closing this issue.

However, I suggest you to check our troubleshooting and FAQ sections on this page: http://aye.comp.nus.edu.sg/parsCit
