### ISSUE TITLE
Problem in specification of output file

### ISSUE THREAD

**Issue by dwatsonbynes** [knmnyn/ParsCit#23]
I tried to execute citeExtract.pl and provided the outfile in the argument. But it doesn't seem to accept the argument. The instructions regarding outfile specification are a little vague. How should I specify it in the command?

![image](https://cloud.githubusercontent.com/assets/6436348/16377965/b50f91cc-3c86-11e6-9c0f-11a6d2bf0d6d.png)

**Comment by cmkumar87** [comment]
The reported issue does not occur in the standard release for the *nix platforms. We do not offer support for the Windows version as we did not develop the system.
