### ISSUE TITLE
: libcrfpp.so.0: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by PatelKrutarth** [knmnyn/ParsCit#29]
I installed ParsCit on 64-bit Ubuntu 16.04. 

I installed CRF++ correctly. But, while running citeExtract.pl with "./citeExtract.pl -m extract_all ../demodata/sample2.txt", it is giving me the error about "wrong ELF class: ELFCLASS64". Which is basically related to the 64-bit library. I also attached screenshot about that. I also run it after replacing "libcrfpp.so.0" compiled on 32-bit Ubuntu. But, I was still getting the similar error.

I would really appreciate if you can help me with this.

-Krutarth
![parsciterror](https://user-images.githubusercontent.com/27706823/30250795-3b3a6522-961a-11e7-8780-fa7976e825ef.png)

**Comment by lwqlwq** [comment]
Hi Krutarth,

This solution works for me. You can have a try.
First, you can download the 64-bits CRF++ (https://taku910.github.io/crfpp/,  CRF++ 0.58) and install it in a standard way.
Then, copy the two newly compiled executables (crf_learn & crf_test) to all locations containing crf_learn & crf_test, also use them to overwrite lt-crf_learn lt-crf_test
    Assume you are now in crfpp folder, with newly compiled crf_learn and crf_test
    $ cp crf_test .libs/lt-crf_test
    $ cp crf_learn .libs/lt-crf_learn

Regards,
Wenqiang

**Comment by PatelKrutarth** [comment]
Thanks a lot, @lwqlwq :) 
That solution worked for me also.

Regards,
Krutarth

**Comment by knmnyn** [comment]
Hi @lwqlwq:

Please add this to the troubleshooting section of the home page.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
