### ISSUE TITLE
Citation text longer than article body: ignoring

### ISSUE THREAD

**Issue by Prateek-Havanur** [knmnyn/ParsCit#34]
i am trying to run ./citeExtract.pl -m extract_all on the [file](https://github.com/Prateek-Havanur/dummy-files/blob/main/test.txt) .I am getting the error  Citation text longer than article body: ignoring . Please let me know if i am missing something. Thanks in advance.

OS:Linux mint
CRF version: 0.57

**Comment by knmnyn** [comment]
Thanks for your bug report.  The regular expressions to find your citations isn't working for your file.  You might try with a different file or try to change the citation parser.  Sorry I don't have more time to diagnose your issue.

**Comment by Prateek-Havanur** [comment]
Thanks for the quick response. Can you please let me know which variables to change in ENV variable or in Config.pm my repository is at the location "/media/prateek/DATA/Code/archive/ParsCit-master" ? I just want to cross verify if i have followed steps to correctly as in INSTALL file. Thanks in advance
