### ISSUE TITLE
Failed to find share dir for dist 'ParsCit'

### ISSUE THREAD

**Issue by Dali-Islam** [knmnyn/ParsCit#36]
I wanted to use parasite for a school project but I have this error that appears and I don't know how to fix it, can someone help me please

when i do this :
./citeExtract.pl -m extract_all ../demodata/sample2.txt

this error appears ;
Failed to find share dir for dist 'ParsCit' at /home/islam/Desktop/plagiat/tools/ParsCit-master/bin/../lib/ParsCit.pm line 20.
BEGIN failed--compilation aborted at ./citeExtract.pl line 43.

**Comment by knmnyn** [comment]
Thanks for your report. This seems to be a misconfiguration on your side, or your path for libraries is set incorrectly. 

Hope you can resolve it! If you do, you can post your solution to your own problem here. 

You might also try our other more updated toolkit [SciWING](https://sciwing.io), which improves over this legacy tool.
