### ISSUE TITLE
Can't locate Path/Tiny.pm in @INC 

### ISSUE THREAD

**Issue by alamshoaib134** [knmnyn/ParsCit#37]
After installing ParsCit and running the ParsCit in demodata it shows me this error. 

```
Can't locate Path/Tiny.pm in @INC (you may need to install the Path::Tiny module) (@INC contains: /home/wing.nus/tools/languages/programming/perl-5.10.0/lib/site_perl/5.10.0 /home/wing.nus/tools/languages/programming/perl-5.10.0/lib/5.10.0 /home/huydhn/perl5/lib /home/harsh.d/ParsCit/bin/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/harsh.d/ParsCit/bin/../lib/ParsCit.pm line 8.
BEGIN failed--compilation aborted at /home/harsh.d/ParsCit/bin/../lib/ParsCit.pm line 8.
Compilation failed in require at ./citeExtract.pl line 43.
BEGIN failed--compilation aborted at ./citeExtract.pl line 43.
```

![parsCit](https://user-images.githubusercontent.com/52914419/179577793-d7db6037-66da-4a77-8128-68a19827bf8f.PNG)

**Comment by knmnyn** [comment]
Hi there, 

Thanks for your interest in this library.  Unfortunately, this code is somewhat out of date and no longer maintained.  You may want to try our newer models that achieve better results.  

https://github.com/abhinavkashyap/sciwing

We are still actively working on a new toolkit, so if you don't need it urgently, you can come back to see our work in this area in the future.

Thanks!

**Comment by knmnyn** [comment]
Hi there,

Thanks for your interest in this library.  Unfortunately, this code is
somewhat out of date and no longer maintained.  You may want to try our
newer models that achieve better results.

https://github.com/abhinavkashyap/sciwing

We are still actively working on a new toolkit, so if you don't need it
urgently, you can come back to see our work in this area in the future.

Thanks!
