### ISSUE TITLE
Wrong path error running citeExtract.pl

### ISSUE THREAD

**Issue by stuaninauts** [knmnyn/ParsCit#38]
When running the `./bin/citeExtract.pl` I got errors after the addition of the `sectLabel` folder (mentioned in the `CHANGELOG` file). 
I had to move the `extractFeature.pl` (`./bin/sectLabel/generictSect`) and `genericSectExtract.pl` (`./bin/sectLabel`) to the `bin` folder for working.

**Comment by knmnyn** [comment]
Thanks for your comments @stuaninauts !  

If you have a fix that you want us to incorporate we will try to pull it in via a pull request.
ParsCit is legacy software at this point so we no longer support it much.  You can refer to the `README` in the GitHub repo for alternative suggestions.
